import "./globals.css";
import type { Metadata } from "next";
import { Sawarabi_Gothic } from "next/font/google";

const gothic = Sawarabi_Gothic({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Adopt me",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${gothic.className}`}>{children}</body>
        </html>
    );
}

